//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PalestrasSafeWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Palestras
    {
        public int Id { get; set; }
        public string NomePalestrante { get; set; }
        public string NomePalestra { get; set; }
        public int Duracao { get; set; }
        public Nullable<int> DiaPalestra { get; set; }
    }
}
